spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        ddl-auto: update  # create, update, validate, or none
        show_sql: true
        format_sql: true




